cc_binary(
    name = "tutorial",
    srcs = ["tutorial.cpp"],
    deps = ["@mlx//:mlx"]
)

cc_binary(
    name = "linear_regression",
    srcs = [
        "linear_regression.cpp",
        "timer.h",
    ],
    deps = ["@mlx//:mlx"]
)

cc_binary(
    name = "logistic_regression",
    srcs = [
        "linear_regression.cpp",
        "timer.h",
    ],
    deps = ["@mlx//:mlx"]
)
